# Generated by Django 3.1.3 on 2021-02-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('fimage', models.FileField(blank=True, null=True, upload_to='static/images/')),
                ('is_veg', models.BooleanField(default=True)),
            ],
        ),
    ]
