# Generated by Django 3.1.3 on 2021-03-11 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20210310_0327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combo',
            name='noOfItems',
        ),
    ]
