# Generated by Django 3.1.3 on 2021-03-11 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_remove_combo_noofitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='combo',
        ),
        migrations.AddField(
            model_name='combo',
            name='comboitem',
            field=models.ManyToManyField(to='menu.Food'),
        ),
    ]
