# Generated by Django 3.1.3 on 2021-03-13 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20210312_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combo',
            name='comboname',
            field=models.CharField(max_length=200),
        ),
    ]
